package com.tsarit.billing.model;

public enum AccountGroup {
    CURRENT_ASSETS,
    FIXED_ASSETS,
    CASH_AND_BANK,
    SUNDRY_DEBTORS,
    CURRENT_LIABILITIES,
    SUNDRY_CREDITORS,
    DUTIES_AND_TAXES,
    CAPITAL_ACCOUNT,
    SALES_ACCOUNTS,
    PURCHASE_ACCOUNTS,
    DIRECT_EXPENSES,
    INDIRECT_EXPENSES,
    DIRECT_INCOME,
    INDIRECT_INCOME
}
