apiVersion: v1
kind: ConfigMap
metadata:
  name: tsar-config
  namespace: tsar-it-production
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/billing_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SERVER_PORT: "8081"
---
apiVersion: v1
kind: Secret
metadata:
  name: tsar-secrets
  namespace: tsar-it-production
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  JWT_SECRET: "tsar_it_enterprise_ultra_secure_jwt_secret_key_2026_super_admin"
